"""made User's  email not nullable

Revision ID: 24946dde0107
Revises: 29c762e5f0e8
Create Date: 2023-12-25 19:34:56.370451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24946dde0107'
down_revision = '29c762e5f0e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
